version: "2"

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    config:
      threshold:
  identical-code:
    config:
      threshold:

exclude_patterns:
  - "tests/**"
  - "docs/**"
  - "nix/**"
  - ".github/**"
  - "templates/**"
